// Verifica visiva locale del Second Brain: serve split/ via HTTP, stubba window.claude (sola lettura), fotografa le schede.
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const path = require('path'), fs = require('fs');
(async () => {
  const base = process.env.SB_URL || 'http://127.0.0.1:8765/index.html';
  const out = process.env.SB_OUT || path.join(__dirname, 'shots'); fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const ctx = await browser.newContext({ viewport: { width: 1380, height: 900 }, locale: 'it-IT' });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  page.on('console', m => { if (m.type() === 'error' && !/CERT_AUTHORITY|favicon/.test(m.text())) errors.push('console: ' + m.text()); });
  await page.addInitScript(() => { window.claude = { use: () => new Promise(r => setTimeout(() => r(null), 30)) }; try { localStorage.clear(); } catch (e) {} });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.waitForTimeout(800);
  const report = {};
  const shot = async (name) => { await page.waitForTimeout(400); await page.screenshot({ path: path.join(out, name + '.png'), fullPage: false }); };
  report.title = await page.title();
  await shot('01-oggi');
  const click = async (sel, name) => { const b = page.locator(sel).first(); if (await b.count()) { await b.click().catch(e => errors.push('click ' + name + ': ' + e.message)); await shot(name); return true; } errors.push('non trovato: ' + sel); return false; };
  await click('#v-dash', '02-commesse');
  report.commessePicker = await page.evaluate(() => Array.from(document.querySelectorAll('.picker .pk b')).map(b => b.textContent));
  await click('#cm-ord', '03-ordini');
  report.ordiniKpi = await page.evaluate(() => Array.from(document.querySelectorAll('.cm-kpi')).map(k => k.textContent.replace(/\s+/g, ' ').trim()).slice(0, 4));
  await click('#cm-cash', '04-cashflow-tutte');
  report.cashTutteHead = await page.evaluate(() => Array.from(document.querySelectorAll('.cf thead th')).map(t => t.textContent).slice(0, 8));
  await click('.picker .pk[data-code="SBC-15-26"]', '05-sel-sbc15');
  await click('#cm-cash', '06-cashflow-sbc15');
  report.cashSbc15 = await page.evaluate(() => Array.from(document.querySelectorAll('.cf tbody tr')).map(r => Array.from(r.children).map(td => td.textContent).join(' | ')));
  report.fornSbc15 = await page.evaluate(() => Array.from(document.querySelectorAll('.cfforn tbody tr')).slice(0, 6).map(r => r.textContent.replace(/\s+/g, ' ').trim()));
  await click('#cm-scad', '07-scadenze');
  report.scadRows = await page.evaluate(() => Array.from(document.querySelectorAll('.otab tbody tr')).slice(0, 8).map(r => r.textContent.replace(/\s+/g, ' ').trim()));
  await click('#c-none', '08-none');
  await click('#cm-scad', '09-scadenze-tutte');
  report.scadKpi = await page.evaluate(() => Array.from(document.querySelectorAll('.cm-kpi')).map(k => k.textContent.replace(/\s+/g, ' ').trim()).slice(0, 3));
  await click('#cm-cli', '09b-clienti');
  report.clienti = await page.evaluate(() => Array.from(document.querySelectorAll('.pcard > b')).slice(0, 5).map(b => b.textContent.replace(/\s+/g, ' ').trim()));
  await click('#cm-ctr', '09c-contratti');
  report.contrattiRows = await page.evaluate(() => document.querySelectorAll('.otab tbody tr').length);
  for (const [sel, name] of [['#v-board', '10-task'], ['#v-bill', '11-denaro'], ['#v-cal', '12-calendario'], ['#v-pers', '13-persone'], ['#v-trip', '14-viaggi']]) await click(sel, name);
  report.cassaHead = await page.evaluate(() => { const el = document.querySelector('#v-bill'); return null; });
  await click('#v-bill', '11b-denaro');
  report.cassaInQuadro = await page.evaluate(() => document.querySelectorAll('.cf tbody tr').length);
  await click('[data-den="flusso"]', '11c-denaro-flusso');
  report.cassa = await page.evaluate(() => Array.from(document.querySelectorAll('.cf tbody tr')).map(r => r.children[0].textContent + ' | ' + Array.from(r.children).slice(1, 5).map(td => td.textContent).join(' | ')));
  report.bozzePronte = await page.evaluate(() => document.querySelectorAll('a.gml.bz').length);
  await click('#v-pers', '13-persone');
  await click('[data-per="forn"]', '13b-fornitori');
  report.fornitori = await page.evaluate(() => ({ n: document.querySelectorAll('.pcard').length, first: Array.from(document.querySelectorAll('.pcard')).slice(0, 3).map(c => c.textContent.replace(/\s+/g, ' ').trim().slice(0, 160)) }));
  await click('[data-solf]:not([disabled])', '13c-sollecito');
  report.solf = await page.evaluate(() => Array.from(document.querySelectorAll('[data-solf]')).slice(0, 3).map(b => b.textContent));
  await click('[data-ordf]', '13d-ordini-fornitore');
  report.ordQ = await page.evaluate(() => (document.querySelector('.fbar') || {}).textContent || null);
  await click('#v-pers', '13-persone');
  await click('[data-per="capi"]', '13e-capi');
  report.deleghe = await page.evaluate(() => Array.from(document.querySelectorAll('.otab tbody tr')).slice(0, 5).map(r => r.textContent.replace(/\s+/g, ' ').trim()));
  await click('#v-trip', '14-viaggi');
  report.viaggiForm = await page.evaluate(() => !!document.getElementById('vr-go'));
  report.chiediHidden = await page.evaluate(() => { const c = document.getElementById('chiedi'); return c ? c.hidden : 'missing'; });
  report.errors = errors;
  fs.writeFileSync(path.join(out, 'report.json'), JSON.stringify(report, null, 1));
  console.log(JSON.stringify(report, null, 1));
  await browser.close();
})().catch(e => { console.error('FATAL', e); process.exit(1); });
